blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://pas.encore.de.site
    about: Cet outil de suivi des problèmes n'est pas destiné aux problèmes de documentation. Veuillez ouvrir un ticket sur le dépôt de documentation.
  - name: 🚀 Déploiement
    url: https://github.com/Kontainer/socle
    about: Cet outil de suivi des problèmes n'est pas destiné aux problèmes de déploiement de la plateforme. Veuillez ouvrir un ticket sur le dépôt de socle.
